export const mockRequisitions = [
  {
    id: 'req-001',
    name: 'REQ-2024-Q1-001 - Technology & Digital Banking',
    positions: [
      { id: 'pos-001', title: 'Senior Software Engineer - Core Banking', requisitionId: 'req-001' },
      { id: 'pos-002', title: 'Data Analyst - Risk Management', requisitionId: 'req-001' },
      { id: 'pos-003', title: 'Cybersecurity Specialist', requisitionId: 'req-001' },
    ],
  },
  {
    id: 'req-002',
    name: 'REQ-2024-Q1-002 - Branch Operations',
    positions: [
      { id: 'pos-004', title: 'Branch Manager - Metro Cities', requisitionId: 'req-002' },
      { id: 'pos-005', title: 'Customer Service Officer', requisitionId: 'req-002' },
      { id: 'pos-006', title: 'Cash Officer', requisitionId: 'req-002' },
    ],
  },
  {
    id: 'req-003',
    name: 'REQ-2024-Q1-003 - Credit & Risk',
    positions: [
      { id: 'pos-007', title: 'Credit Analyst - Corporate Banking', requisitionId: 'req-003' },
      { id: 'pos-008', title: 'Risk Management Officer', requisitionId: 'req-003' },
    ],
  },
];

export const mockCandidates = [
  // Position 1: Senior Software Engineer - Core Banking (30 candidates)
  {
    id: 'cand-001',
    name: 'Rajesh Kumar',
    skills: ['Java', 'Spring Boot', 'Microservices', 'Oracle DB'],
    rating: 4.5,
    contact: '+91-9876543210',
    location: 'Mumbai, Maharashtra',
    stage: 'Applied',
    positionId: 'pos-001',
    experience: '8 years',
    source: 'LinkedIn',
  },
  {
    id: 'cand-002',
    name: 'Priya Sharma',
    skills: ['Python', 'Banking Systems', 'Finacle', 'SQL'],
    rating: 4.8,
    contact: '+91-9876543211',
    location: 'Bangalore, Karnataka',
    stage: 'Shortlisted',
    positionId: 'pos-001',
    experience: '6 years',
    source: 'Naukri',
  },
  {
    id: 'cand-003',
    name: 'Amit Patel',
    skills: ['C++', 'Core Banking', 'Unix', 'Oracle'],
    rating: 4.2,
    contact: '+91-9876543212',
    location: 'Ahmedabad, Gujarat',
    stage: 'Interview Scheduled',
    positionId: 'pos-001',
    experience: '10 years',
    source: 'LinkedIn',
  },
  {
    id: 'cand-004',
    name: 'Sneha Reddy',
    skills: ['Java', 'Kafka', 'Redis', 'AWS'],
    rating: 4.7,
    contact: '+91-9876543213',
    location: 'Hyderabad, Telangana',
    stage: 'Selected for Next Round',
    positionId: 'pos-001',
    experience: '7 years',
    source: 'Naukri',
  },
  {
    id: 'cand-005',
    name: 'Vikram Singh',
    skills: ['React', 'Node.js', 'Banking APIs', 'Docker'],
    rating: 4.3,
    contact: '+91-9876543214',
    location: 'Delhi, NCR',
    stage: 'Applied',
    positionId: 'pos-001',
    experience: '5 years',
    source: 'LinkedIn',
  },
  {
    id: 'cand-011',
    name: 'Arjun Mehta',
    skills: ['Java', 'Spring', 'Hibernate', 'PostgreSQL'],
    rating: 4.4,
    contact: '+91-9876543220',
    location: 'Mumbai, Maharashtra',
    stage: 'Applied',
    positionId: 'pos-001',
    experience: '7 years',
    source: 'Naukri',
  },
  {
    id: 'cand-012',
    name: 'Divya Krishnan',
    skills: ['Python', 'Django', 'REST APIs', 'MySQL'],
    rating: 4.6,
    contact: '+91-9876543221',
    location: 'Bangalore, Karnataka',
    stage: 'Applied',
    positionId: 'pos-001',
    experience: '5 years',
    source: 'LinkedIn',
  },
  {
    id: 'cand-013',
    name: 'Rohan Desai',
    skills: ['JavaScript', 'Angular', 'TypeScript', 'MongoDB'],
    rating: 4.1,
    contact: '+91-9876543222',
    location: 'Pune, Maharashtra',
    stage: 'Applied',
    positionId: 'pos-001',
    experience: '4 years',
    source: 'Naukri',
  },
  {
    id: 'cand-014',
    name: 'Kavita Nair',
    skills: ['Java', 'Microservices', 'Kubernetes', 'Docker'],
    rating: 4.7,
    contact: '+91-9876543223',
    location: 'Kochi, Kerala',
    stage: 'Applied',
    positionId: 'pos-001',
    experience: '9 years',
    source: 'LinkedIn',
  },
  {
    id: 'cand-015',
    name: 'Sanjay Gupta',
    skills: ['C#', '.NET Core', 'Azure', 'SQL Server'],
    rating: 4.3,
    contact: '+91-9876543224',
    location: 'Delhi, NCR',
    stage: 'Applied',
    positionId: 'pos-001',
    experience: '6 years',
    source: 'Naukri',
  },
  {
    id: 'cand-016',
    name: 'Pooja Rao',
    skills: ['Python', 'Flask', 'AWS Lambda', 'DynamoDB'],
    rating: 4.5,
    contact: '+91-9876543225',
    location: 'Bangalore, Karnataka',
    stage: 'Applied',
    positionId: 'pos-001',
    experience: '5 years',
    source: 'LinkedIn',
  },
  {
    id: 'cand-017',
    name: 'Anil Kumar',
    skills: ['Java', 'Spring Boot', 'Kafka', 'Redis'],
    rating: 4.2,
    contact: '+91-9876543226',
    location: 'Hyderabad, Telangana',
    stage: 'Applied',
    positionId: 'pos-001',
    experience: '8 years',
    source: 'Naukri',
  },
  {
    id: 'cand-018',
    name: 'Neha Joshi',
    skills: ['React', 'Redux', 'Node.js', 'Express'],
    rating: 4.6,
    contact: '+91-9876543227',
    location: 'Mumbai, Maharashtra',
    stage: 'Applied',
    positionId: 'pos-001',
    experience: '6 years',
    source: 'LinkedIn',
  },
  {
    id: 'cand-019',
    name: 'Manish Agarwal',
    skills: ['Java', 'Oracle', 'PL/SQL', 'Unix'],
    rating: 4.0,
    contact: '+91-9876543228',
    location: 'Kolkata, West Bengal',
    stage: 'Applied',
    positionId: 'pos-001',
    experience: '10 years',
    source: 'Naukri',
  },
  {
    id: 'cand-020',
    name: 'Swati Mishra',
    skills: ['Python', 'Data Engineering', 'Spark', 'Hadoop'],
    rating: 4.8,
    contact: '+91-9876543229',
    location: 'Pune, Maharashtra',
    stage: 'Applied',
    positionId: 'pos-001',
    experience: '7 years',
    source: 'LinkedIn',
  },
  {
    id: 'cand-021',
    name: 'Kunal Shah',
    skills: ['JavaScript', 'Vue.js', 'Webpack', 'REST APIs'],
    rating: 4.4,
    contact: '+91-9876543230',
    location: 'Ahmedabad, Gujarat',
    stage: 'Applied',
    positionId: 'pos-001',
    experience: '5 years',
    source: 'Naukri',
  },
  {
    id: 'cand-022',
    name: 'Rina Kapoor',
    skills: ['Java', 'Spring Cloud', 'Microservices', 'AWS'],
    rating: 4.7,
    contact: '+91-9876543231',
    location: 'Bangalore, Karnataka',
    stage: 'Applied',
    positionId: 'pos-001',
    experience: '8 years',
    source: 'LinkedIn',
  },
  {
    id: 'cand-023',
    name: 'Nitin Verma',
    skills: ['C++', 'STL', 'Boost', 'Linux'],
    rating: 4.1,
    contact: '+91-9876543232',
    location: 'Noida, Uttar Pradesh',
    stage: 'Applied',
    positionId: 'pos-001',
    experience: '9 years',
    source: 'Naukri',
  },
  {
    id: 'cand-024',
    name: 'Geeta Iyer',
    skills: ['Python', 'FastAPI', 'PostgreSQL', 'Docker'],
    rating: 4.5,
    contact: '+91-9876543233',
    location: 'Chennai, Tamil Nadu',
    stage: 'Applied',
    positionId: 'pos-001',
    experience: '6 years',
    source: 'LinkedIn',
  },
  {
    id: 'cand-025',
    name: 'Suresh Pillai',
    skills: ['Java', 'JPA', 'Hibernate', 'MySQL'],
    rating: 4.3,
    contact: '+91-9876543234',
    location: 'Kochi, Kerala',
    stage: 'Applied',
    positionId: 'pos-001',
    experience: '7 years',
    source: 'Naukri',
  },
  {
    id: 'cand-026',
    name: 'Anjali Deshmukh',
    skills: ['React', 'TypeScript', 'GraphQL', 'Apollo'],
    rating: 4.6,
    contact: '+91-9876543235',
    location: 'Pune, Maharashtra',
    stage: 'Applied',
    positionId: 'pos-001',
    experience: '5 years',
    source: 'LinkedIn',
  },
  {
    id: 'cand-027',
    name: 'Harish Shetty',
    skills: ['Java', 'Spring Security', 'OAuth', 'JWT'],
    rating: 4.4,
    contact: '+91-9876543236',
    location: 'Bangalore, Karnataka',
    stage: 'Applied',
    positionId: 'pos-001',
    experience: '8 years',
    source: 'Naukri',
  },
  {
    id: 'cand-028',
    name: 'Rekha Menon',
    skills: ['Python', 'Pandas', 'NumPy', 'Scikit-learn'],
    rating: 4.2,
    contact: '+91-9876543237',
    location: 'Hyderabad, Telangana',
    stage: 'Applied',
    positionId: 'pos-001',
    experience: '6 years',
    source: 'LinkedIn',
  },
  {
    id: 'cand-029',
    name: 'Prakash Reddy',
    skills: ['Java', 'WebLogic', 'JMS', 'Oracle'],
    rating: 4.0,
    contact: '+91-9876543238',
    location: 'Mumbai, Maharashtra',
    stage: 'Applied',
    positionId: 'pos-001',
    experience: '11 years',
    source: 'Naukri',
  },
  {
    id: 'cand-030',
    name: 'Shruti Bose',
    skills: ['JavaScript', 'React Native', 'Mobile Development', 'Redux'],
    rating: 4.5,
    contact: '+91-9876543239',
    location: 'Kolkata, West Bengal',
    stage: 'Applied',
    positionId: 'pos-001',
    experience: '5 years',
    source: 'LinkedIn',
  },
  {
    id: 'cand-031',
    name: 'Vivek Pandey',
    skills: ['Java', 'Tomcat', 'Maven', 'Git'],
    rating: 4.3,
    contact: '+91-9876543240',
    location: 'Lucknow, Uttar Pradesh',
    stage: 'Applied',
    positionId: 'pos-001',
    experience: '7 years',
    source: 'Naukri',
  },
  {
    id: 'cand-032',
    name: 'Lakshmi Narayan',
    skills: ['Python', 'TensorFlow', 'Machine Learning', 'AI'],
    rating: 4.9,
    contact: '+91-9876543241',
    location: 'Bangalore, Karnataka',
    stage: 'Applied',
    positionId: 'pos-001',
    experience: '6 years',
    source: 'LinkedIn',
  },
  {
    id: 'cand-033',
    name: 'Ravi Shankar',
    skills: ['Java', 'Jenkins', 'CI/CD', 'DevOps'],
    rating: 4.4,
    contact: '+91-9876543242',
    location: 'Chennai, Tamil Nadu',
    stage: 'Applied',
    positionId: 'pos-001',
    experience: '8 years',
    source: 'Naukri',
  },
  {
    id: 'cand-034',
    name: 'Pallavi Kulkarni',
    skills: ['React', 'Next.js', 'Tailwind CSS', 'Vercel'],
    rating: 4.6,
    contact: '+91-9876543243',
    location: 'Pune, Maharashtra',
    stage: 'Applied',
    positionId: 'pos-001',
    experience: '4 years',
    source: 'LinkedIn',
  },
  {
    id: 'cand-035',
    name: 'Mahesh Babu',
    skills: ['Java', 'SOA', 'BPEL', 'Web Services'],
    rating: 4.1,
    contact: '+91-9876543244',
    location: 'Hyderabad, Telangana',
    stage: 'Applied',
    positionId: 'pos-001',
    experience: '10 years',
    source: 'Naukri',
  },

  // Position 2: Data Analyst - Risk Management
  {
    id: 'cand-006',
    name: 'Ananya Iyer',
    skills: ['SQL', 'Tableau', 'Power BI', 'Risk Analytics'],
    rating: 4.6,
    contact: '+91-9876543215',
    location: 'Chennai, Tamil Nadu',
    stage: 'Applied',
    positionId: 'pos-002',
    experience: '4 years',
    source: 'Naukri',
  },
  {
    id: 'cand-007',
    name: 'Karthik Menon',
    skills: ['Python', 'ML', 'Credit Risk', 'SAS'],
    rating: 4.9,
    contact: '+91-9876543216',
    location: 'Pune, Maharashtra',
    stage: 'Shortlisted',
    positionId: 'pos-002',
    experience: '6 years',
    source: 'LinkedIn',
  },

  // Position 3: Cybersecurity Specialist
  {
    id: 'cand-008',
    name: 'Deepa Nair',
    skills: ['Cybersecurity', 'Ethical Hacking', 'SIEM', 'Firewall'],
    rating: 4.4,
    contact: '+91-9876543217',
    location: 'Kochi, Kerala',
    stage: 'Applied',
    positionId: 'pos-003',
    experience: '9 years',
    source: 'Naukri',
  },
  {
    id: 'cand-009',
    name: 'Rahul Verma',
    skills: ['ISO 27001', 'Network Security', 'Penetration Testing'],
    rating: 4.1,
    contact: '+91-9876543218',
    location: 'Mumbai, Maharashtra',
    stage: 'Applied',
    positionId: 'pos-003',
    experience: '7 years',
    source: 'LinkedIn',
  },

  // Position 4: Branch Manager - Metro Cities
  {
    id: 'cand-010',
    name: 'Meera Joshi',
    skills: ['Banking Operations', 'Customer Relations', 'Leadership'],
    rating: 4.5,
    contact: '+91-9876543219',
    location: 'Vadodara, Gujarat',
    stage: 'Shortlisted',
    positionId: 'pos-004',
    experience: '12 years',
    source: 'Naukri',
  },
];
